---
- name: Create email-exporter user
  register: app_user
  user:
    name: "{{ email_exporter_user }}"
    home: /var/lib/{{ email_exporter_user }}
    shell: /usr/sbin/nologin
    system: true
    comment: User for the IMAP to S3 mail archiver

- name: Install uv
  include_role:
    name: maneyko.roles.uv
  vars:
    uv_users: ["{{ email_exporter_user }}"]

- name: Clone email-exporter repo
  git:
    accept_hostkey: true
    repo: "{{ email_exporter_repo }}"
    version: "{{ config.version | default('main') }}"
    dest: "{{ email_exporter_root }}"

- name: Set email-exporter file permissions
  changed_when: false
  shell: |
    chown -R {{ config.owner }}:{{ email_exporter_user }} {{ email_exporter_root }}
    find {{ email_exporter_root }} -type d -exec chmod 2750 {} +
    find {{ email_exporter_root }} -type f -exec chmod g-w,o= {} +

- name: Create email-exporter secrets directory
  file:
    state: directory
    path: "{{ email_exporter_conf }}/secrets"
    owner: "{{ config.owner }}"
    group: "{{ email_exporter_user }}"
    mode: '0750'

- name: Write email-exporter account secrets
  loop: "{{ secrets.users }}"
  no_log: true
  copy:
    content: "{{ item }}"
    dest: "{{ email_exporter_conf }}/secrets/{{ (item | regex_findall(email_exporter_username_re)) | first }}.toml"
    owner: "{{ config.owner }}"
    group: "{{ email_exporter_user }}"
    mode: '0640'

- name: Write email-exporter environment
  copy:
    dest: "{{ email_exporter_conf }}/environment"
    content: |
      BUCKET_NAME={{ config.bucket_name }}
    owner: "{{ config.owner }}"
    mode: '0644'

- name: Create AWS config directory
  file:
    state: directory
    path: "{{ app_user.home }}/.aws"
    owner: "{{ email_exporter_user }}"
    group: "{{ email_exporter_user }}"
    mode: '0700'

- name: Write AWS region
  copy:
    dest: "{{ app_user.home }}/.aws/config"
    content: |
      [default]
      region = {{ email_exporter_aws_region }}
    owner: "{{ email_exporter_user }}"
    group: "{{ email_exporter_user }}"
    mode: '0644'

- name: Write AWS credentials
  no_log: true
  copy:
    dest: "{{ app_user.home }}/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ secrets.aws.credentials.access_key }}
      aws_secret_access_key = {{ secrets.aws.credentials.secret_key }}
    owner: "{{ email_exporter_user }}"
    group: "{{ email_exporter_user }}"
    mode: '0600'

- name: Install systemd units
  loop: [email-exporter.service, email-exporter.timer]
  copy:
    remote_src: true
    src: "{{ email_exporter_root }}/etc/systemd/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'

- name: Enable email-exporter timer
  systemd_service:
    name: email-exporter.timer
    daemon_reload: true
    enabled: true
    state: started
